# Training configuration for ResNet trained on ImageNet on GPUs.
# Reaches > 76.1% within 90 epochs.
# Note: This configuration uses a scaled per-replica batch size based on the number of devices.
runtime:
  model_dir: null
  mode: 'train_and_eval'
  distribution_strategy: 'off'
  enable_xla: True
  run_eagerly: False
  num_gpus: 1
  loss_scale: 'dynamic'
train_dataset:
  name: 'imagenet2012'
  data_dir: null
  builder: 'records'
  split: 'train'
  image_size: 224
  num_classes: 1000
  num_examples: 1281167
  batch_size: 256
  use_per_replica_batch_size: True
  dtype: 'float16'
  mean_subtract: True
  standardize: True
validation_dataset:
  name: 'imagenet2012'
  data_dir: null
  builder: 'records'
  split: 'validation'
  image_size: 224
  num_classes: 1000
  num_examples: 50000
  batch_size: 256
  use_per_replica_batch_size: True
  dtype: 'float16'
  mean_subtract: True
  standardize: True
model:
  model_name: 'resnet50v2'
  optimizer:
    name: 'momentum'
    momentum: 0.9
    decay: 0.9
    epsilon: 0.001
  learning_rate:
    name: 'piecewise_constant_with_warmup'
  loss:
    label_smoothing: 0.1
train:
  resume_checkpoint: True
  epochs: 90
evaluation:
  epochs_between_evals: 1
